spring:
  datasource:
    url: jdbc:postgresql://ep-royal-river-45970815.eu-central-1.aws.neon.tech/reports?user=tilenmiklavic&password=U65pDcNzgwuj&sslmode=require
    username: tilenmiklavic
    password: U65pDcNzgwuj
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
