apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
        - image: tmiklavic/reports:latest
          name: reports
          imagePullPolicy: Always
          env:
            - name: DB_CONNECTIONURL
              value: jdbc:postgresql://ep-royal-river-45970815.eu-central-1.aws.neon.tech/users?sslmode=require
            - name: DB_USERNAME
              value: tilenmiklavic
#              valueFrom:
#                secretKeyRef:
#                  name: mydbsecret
#                  key: username
            - name: DB_PASSWORD
              value: U65pDcNzgwuj
#              valueFrom:
#                secretKeyRef:
#                  name: mydbsecret
#                  key: password
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: mydbsecret
                  key: base_url
          ports:
            - containerPort: 8080
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: reports
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: reports
